### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by luca-s** [SeisComP3/bgr-mags-addons#2]
Dear developers,

I am just trying to understand the status of this module before spending some time in testing it. 

Is there a particular reason why this module is not bundled together with seiscomp3 and it is in a separate module instead? Has the module limitations or big issues so that it is not considered for proper seiscomp3 integration?

thank you.

**Comment by gempa-jabe** [comment]
The module has been developed for a particular project called MAGS and was still in testing mode after its implementation was finished. As we (gempa) do not use it on a daily basis and I personally haven't gotten much feedback from other users about the usability and reliability, it is kept in a separate repository. Furthermore the code belongs to BGR. Inclusion into SC3 means additional code maintenance and support for something that is maybe not used. I don't know of big issues or limitations, just missing feedback so far.

**Comment by luca-s** [comment]
Thank you very much for the reply.
